version: "3"
services:
  api-database:
    image: mongo:3.2.4
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles
  api-database-seed:
    image: mongo:3.2.4
    links:
      - api-database
    volumes:
      - ./database:/database
    command:
      /database/import.sh
  api:
    image: api
    ports:
      - 8080:8080
    links:
      - api-database
