version: "3"
services:
  api-database:
    image: mongo:latest
    container_name: "api-database"
    ports:
      - 27017:27017
  api-database-seed:
    image: mongo:latest
    container_name: "api-database-seed"
    links:
      - api-database
    volumes:
      - ./database:/database
    command:
      /database/import.sh
  api:
    image: api:latest
    container_name: "api"
    ports:
      - 8080:8080
    links:
      - api-database
